# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5d2f24b3477fe407c75bb53bc6ea1bc0233e468c1e198f6ab0c61bc6ceabccc8f47d7cd3c1b164a0b1587c0a77c13db7766759847be7e9f3a5959292968acad

test:
  secret_key_base: ed93aee7d47e0839feb4fc0e637e5eedbf7a9f3b570dbe0a109d4ff8ba1c540a72ba9673e9cbfed0c4fe150cde7aea71f7162ca9fc962af044aa722f51adeea6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
